version: "3.3"
services:
    service1:
        build: .
        ports:
            - 3001:3000

    service2:
        build: .
        ports:
            - 3002:3000

    logs-app:
        build: ../
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock